### ISSUE TITLE
Write the security blueprint document scope (section 1)

### ISSUE THREAD

**Issue by waltminer** [automotive-grade-linux/docs-agl#1]

**Comment by waltminer** [comment]
From AGL Security Summit:

AGL as the black box
- IVI system
- Telematics system
- Instrument Cluster
- Other ECUs?

**Comment by johnnyvie** [comment]
Here is a proposal for the scope to be reviewed at tomorrows meeting.

## Scope

The Security Blueprint will document the security features that are included as part of Automotive Grade Linux (AGL), identify areas that need to be addressed from a security perspective as part of AGL, provide guidance around existing technologies and solutions, identify areas that need to be worked on in the future as part of AGL, and provide recommendations and requirements for areas that are out of scope of this document and AGL.

This document will focus on the following key areas:
- Security Concepts
- Threat Modelling
- Adversaries
- Attack Surface
- Platform Security
- Threat Analysis

It is not the intention for this document or Automotive Grade Linux in general to solve all security related issues.

**Comment by hammadahmedirdeto** [comment]
I think this is done. Going to close.
