### ISSUE TITLE
Provide details of integrated OTA approach

### ISSUE THREAD

**Issue by codders** [automotive-grade-linux/docs-agl#107]
I know that my perspective is not completely neutral here, but it seems a shame not to mention anywhere the support for OTA that is integrated into the platform, or to reference the implementation of Uptane (https://uptane.github.io) implementation available in meta-agl. Those details would be relevant in the FOTA section.

**Comment by kooltux** [comment]
Please provide the documents to be added in markdown format, adjust the site TOC and make a PR. I can help for the details on how to integrate a new section about SOTA/FOTA into the doc site. If it's just adding a section in an existing document, it's even easier and you can probably update directly through github editor.
