### ISSUE TITLE
Incorporate Phil's adversary list into section 04-Adversaries

### ISSUE THREAD

**Issue by waltminer** [automotive-grade-linux/docs-agl#2]
Phil's document can be found at. https://docs.google.com/document/d/1XTBG6QZQuLvRlY3WAAPYQZ5TN-cH994y-BtvKKmmSKo/pub

Checking with Phil on permission to reuse.

**Comment by cajun-rat** [comment]
Yes that is fine

**Comment by waltminer** [comment]
Hammad will take a look at adding this to the document.

**Comment by hammadahmedirdeto** [comment]
This has been merged
